image: node:14-alpine

cache: {}

stages:
  - verify
  - build
  - publish

verify:
  stage: verify
  cache: {}
  tags:
    - docker
  script:
    - npm ci --loglevel warn
    - npm test

build:artifact:
  stage: build
  cache: {}
  tags:
    - docker
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  script:
    - npm ci --loglevel warn --only=production
  artifacts:
    paths:
      - app
      - bin
      - config
      - node_modules
      - Dockerfile
      - .dockerignore
      - package.json
      - package-lock.json
    expire_in: 1 hour

publish:docker:
  stage: publish
  image: docker:git
  services:
    - docker:dind
  variables:
    GIT_STRATEGY: none
  cache: {}
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  tags:
    - docker
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull --rm -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker rmi "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
